# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Metalama
email: hello@postsharp.net
base_path: "" # the subpath of your site, e.g. /blog
url: "https://metalama.net" # the base hostname & protocol for your site


strict_front_matter: true

title_separator: "|"

  
exclude: ["*.ps1", "README.md", "package.json", "package-lock.json", "gulpfile.js", "eng/**"]
include: ["solutions/*.md"]

sass:
  style: compressed
  sourcemap: always
  silence_deprecations: ["import", "slash-div"]


defaults: 
  - scope:
      path: "metalama-email-course"
    values:
      layout: "email-course" 
      images_url: "https://emails.postsharp.net/metalama-email-course/images"
  - scope:
      path: "metalama-awareness-campagn"
    values:
      layout: "instantly" 
      images_url: "https://emails.postsharp.net/metalama-awareness-campaign/images"

markdown: kramdown
kramdown:
  highlighter: rouge
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    line_numbers: false
